[application]
name = "Library Build Management"

[bundle]
identifier = "com.juanpiece.library-build-management"
publisher = "JuanPiece"
version = "0.0.1"
icon = ["assets/icon.png"]

[web.app]

# HTML title tag content
title = "hot_dog"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
